### ISSUE TITLE
Create system to ease the use of localized strings

### ISSUE THREAD

**Issue by vikigenius** [WittleWolfie/WW-Blueprint-Core#18]
It would be nice if methods such as `SetLocalizedName` have an overload to take standard strings and internally convert into a localized string.

It seems like implicit type conversion is not supported as an extension method and might be too much magic anyways. So actual overloads seems to be the way to go.

Can take ideas from Vek's localization helpers.

Can have a static dictionary in the `BlueprintTool` `LocalizationMapping` that maps string to localized string.

**Comment by WittleWolfie** [comment]
TODO:
-Make use of LocalString in API
-Add Harmony patch to load localization pack

**Comment by WittleWolfie** [comment]
Everything will launch in 2.1. Currently I'm opting not to allow implicitly creating strings but you can now write your strings in a JSON file and reference using key directly.
