### ISSUE TITLE
Clarify parameter comments for blueprint Guids

### ISSUE THREAD

**Issue by vikigenius** [WittleWolfie/WW-Blueprint-Core#19]
```cs
CharacterClassConfigurator.New(BlueprintName, BlueprintGuid)
    .SetEquipmentEntities(wizardClass.EquipmentEntities) // This shows error
    .SetMaleEquipmentEntities(wizardClass.MaleEquipmentEntities) // This is ok
    .SetFemaleEquipmentEntities(wizardClass.FemaleEquipmentEntities) // This is ok
    .Configure();
```

So it seems like `EquipmentEntities` is of type 
```cs
ReferenceArrayProxy<KingmakerEquipmentEntity, KingmakerEquipmentEntityReference>
```
But `SetEquipmentEntities` expects a string?

While `MaleEquipmentEntities` and `FemaleEquipmentEntities` are of type `EquipmentEntityLink[]` which is handled correctly

**Comment by WittleWolfie** [comment]
EquipmentEntities is an array of type KingmakerEquipmentEntityReference which is actually a blueprint reference. It's looking for the Guid. I'll update the parameter descriptions now that it's auto generated to make this clear.

**Comment by WittleWolfie** [comment]
Resolved w/ the Blueprint<T, TRef> type, implicit constructors, and parameter comments in 2.0.
