### ISSUE TITLE
Add tools for working with Encyclopedia tags.

### ISSUE THREAD

**Issue by Aegonek** [WittleWolfie/WW-Blueprint-Core#26]
I'm gonna work on adding EncyclopediaTool to BlueprintCore, based on Vek existing tool in TTT. I am currently in need of this.

Reporting here so we don't do duplicate work.

**Comment by Aegonek** [comment]
If you could assign this issue to me, that would be great - I am unable to do that. For context, I am a bit new to open source stuff 😁

**Comment by WittleWolfie** [comment]
👍 Thanks for putting it as an issue! This is on my long list of things to do but right now I'm rebuilding the code gen to remove the text template processing. It's too painful when changes are needed to common elements in both manual and auto-generated code.

**Comment by WittleWolfie** [comment]
@Aegonek anything else you're planning here?

**Comment by Aegonek** [comment]
I don't really have time for modding lately, I'm quite busy 😞

**Comment by Aegonek** [comment]
Unless you asked for the issue, the answer for that is "no" 🤣

**Comment by WittleWolfie** [comment]
@Aegonek Understood. Come back when you can :)
