### ISSUE TITLE
Request improved levelEntry support

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#35]
I cannot find any way to use blueprintcore to modify the contents of progression levelentries. Can only add / remove the levelentries themselves.

This is not particularly useful.

Suggest ability to add elements to levelentries by level (creating if missing) and remove elements selected by predicate.

**Comment by WittleWolfie** [comment]
That makes sense and shouldn't be too hard. I'll see if I can put it in the next feature release.

**Comment by WittleWolfie** [comment]
The interim solution would be to use OnConfigure():

`ProgressionConfigurator.For(SomeProgression).OnConfigure(bp => bp.LevelEntries...).Configure()`

**Comment by WittleWolfie** [comment]
Still not sure how I want to do this but I think this is a good enhancement to target for 2.1 release.

**Comment by WittleWolfie** [comment]
Launching w/ 2.1. Expecting to rollout tomorrow.
