### ISSUE TITLE
ProgressionConfigurator: Improve AddToClasses with better methods.

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#51]
AddToClasses is a PITA to use - there's no reason for it to require a non-params array of BlueprintProgression.ClassWithLevel or to not have an alternate signature that just takes BlueprintCharacterClassReferences.

Please improve the available input with less boilerplates.

In general any method that takes a single array input should be params-enabled.

**Comment by pheonix99** [comment]
Nevermind found SetClasses

**Comment by WittleWolfie** [comment]
Both should currently take params. This could have an override which takes anonymous tuples if that helps:

`params (Blueprint<BlueprintCharacterClassReference> class, int level)[]`
