### ISSUE TITLE
BuffConfigurator side fix for persistant buff icon issue

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#52]
At least some of the persistant buff icon issues are cause by BlueprintBuff.FxOnRemove being unset causing an NPE during the buff removal process.

Would it be possible for BuffConfigurator to automatically set that field to an empty PrefabLink if it isn't set at Configure() time?

**Comment by WittleWolfie** [comment]
Yup! This is on the 2.1 roadmap: https://github.com/WittleWolfie/WW-Blueprint-Core/issues/33.

I think I'll probably just take the same approach as w/ Component / Action / Condition construction and use empty constants for types that shouldn't be null. Currently I believe that's:

* PrefabLink
* Blueprint References
* ActionList
* ConditionsChecker
* ContextDiceValue
* ContextVAlue
* LocalizedString

If you come across others let me kno!

**Comment by WittleWolfie** [comment]
Fixed w/ 2.1.
