### ISSUE TITLE
Restore Param version of AddAbilityVariants

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#53]
V1.whatever had a params method for setting ability variants, it's gone now.

Please restore, params is very convenient.

**Comment by WittleWolfie** [comment]
Easy to resolve as a one-off fix, I'll have to think more on this problem generally. It might be reasonable to just allow any method w/ a single enumerable parameter to use params syntax but it requires a fair bit of work to do.

**Comment by WittleWolfie** [comment]
Launching w/ 2.1.
