### ISSUE TITLE
Unbreak AddLootItemsPackFixed

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#55]
The 1.x version of this took the exact same base paramaters (LootItem item, Value int) and did not need a merge component to not crash the game during build.

.AddComponent<LootItemsPackFixed>(x => {
                    x.m_Item = LootItem;
                    x.m_Count = Count;
}
Works just fine - AddLootItemsPackFixed should just be a glorified wrapper for that. Please revert.

**Comment by WittleWolfie** [comment]
Looking into this, it's happening because BPCore incorrectly identified this as a Unique component. In reality it is not, AllowMultiple should check inheritance to generate the correct API.

This is a nasty bug so I'll get a fix out as soon as I can.
