### ISSUE TITLE
Request feature: Prefab Link Convenience Creation Method

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#57]
It looks like I need to manually add the dashes into PrefabLink GUIDs and this is annoying.

Could we get a convenience builder like the fixed duration one?

**Comment by pheonix99** [comment]
Wait this may not be the issue I'm having.

**Comment by WittleWolfie** [comment]
Some other modders had issues when using upper-case letters. Technically spec for GUID is alphanumeric, lower-case. When handling blueprint guids BPCore calls `ToLower()`, maybe that's something useful for PrefabLink creation?
