### ISSUE TITLE
Feature Request: More Convenience Constructors for ContextDurationValue

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#63]
Can we get something like ContextDuration.Fixed for per-level and die-roll durations?

**Comment by WittleWolfie** [comment]
This will launch w/ 2.1.

Note that per-level can't really be done this way because it's an interaction between components. i.e. To achieve 1 Round/Level you need to create a duration using a ContextValue based on a Rank, and then you need to create a ContextRankConfig with the same Rank:

```C#
// Use this with whatever components/conditions/actions need this duration
var roundsPerLevel = ContextDuration.Variable(ContextValues.Rank());
// Add this to the blueprint components
var rankConfig = ContextRankConfigs.CharacterLevel();
```
