### ISSUE TITLE
Tutorial Nits

### ISSUE THREAD

**Issue by WittleWolfie** [WittleWolfie/WW-Blueprint-Core#76]
- Missing a ")" in Skald's Vigor tutorial Buffconfigurator (end of the conditional)
- Actually Magical Aptitude should be Untyped
- Should link to COP implementations, especially for Hurtful (including linking to TTT-Core transpiler)

**Comment by Envibel** [comment]
In addition to the ")" mentioned above, there's a missing ")" here:
![image](https://user-images.githubusercontent.com/113065492/188974325-e0fcd7ad-e74e-472a-8512-9317f503593f.png)

**Comment by WittleWolfie** [comment]
Fixed and live
