### ISSUE TITLE
Documentation issue - ILRepack section of guide consistantly errors

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#83]
The publicise assembly and condense with ILRepack guide consistently errors. 

I get
The source file "C:\Users\<PERSONAL DATA REDACTED>\source\repos\PhoenixsCantrips\lib\Assembly-CSharp_public.dll" does not exist.	PhoenixsCantrips	C:\Users\<PERSONAL DATA REDACTED>\source\repos\PhoenixsCantrips\PhoenixsCantrips\PhoenixsCantrips.csproj	56	

Commenting out line 56 seems to make it work - it looks like the assembly is being renamed and then there's an attempt to rename it via move after.

**Comment by WittleWolfie** [comment]
This is a holdover caused indirectly by publicize script. The publicizer now skips its operation if the hash of the DLL didn't change (i.e. you run clean twice when the game assembly hasn't changed). This in turn causes a whole series of failures.

BPCoreTemplate project has the correct configuration, updated the get started docs to include the updated publicize task.
