### ISSUE TITLE
Add FeatureGroups[] param to FeatureSelectionConfigurator

### ISSUE THREAD

**Issue by pheonix99** [WittleWolfie/WW-Blueprint-Core#84]
The FeatureGroups[] param on FeatureConfigurator that auto-adds features to the appropriate selectors is very handy.

Would be extremely nice to have on FeatureSelectionConfigurator as well.

**Comment by WittleWolfie** [comment]
In 2.7.6

**Comment by WittleWolfie** [comment]
Note that this doesn't have all the logic for automatically populating the complicated cases still (Ranger, Teamwork Feats). Hopefully you don't need but if you do you can just create the BP then modify it using `FeatureConfigurator`... At least it should work but if you have issues lmk.

**Comment by WittleWolfie** [comment]
... I forgot a key part of this.

**Comment by WittleWolfie** [comment]
Whatever it's all in 2.7.7 I made it feature parity so it'll handle all the wonky cases.
