### ISSUE TITLE
Cavalier is bugged? Pheonix told me to post this error log here.

### ISSUE THREAD

**Issue by Teraunce** [WittleWolfie/WW-Blueprint-Core#86]
{"LogEvent":{"Severity":0,"Channel":"[TomeOfTheFirebird] ","Message":"Patched Icon on: af2b526de7134f6e8f563eea068ae545 - BloodragerPhoenixFire","StackTrace":[]}}
{"LogEvent":{"Severity":1,"Channel":"Mods","Message":"BlueprintCore.BlueprintConfigurator: CavalierTacticianAbility (BlueprintAbility) failed validation:\r\n  * Too many AbilityApplyEffect components. Only AbilityApplyFact applies..\r\n","StackTrace":["BlueprintCore.Utils.LogWrapper.Warn(System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.UnitLogic.Abilities.AbilityConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.AddBuffToAbilityApplyFact(Kingmaker.UnitLogic.Buffs.Blueprints.BlueprintBuff,BlueprintCore.Utils.Blueprint`1[Kingmaker.Blueprints.BlueprintReference`1[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility]]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.PopulateSelections(Kingmaker.Blueprints.Classes.BlueprintFeature,System.Collections.Generic.HashSet`1[Kingmaker.Blueprints.BlueprintFeatureSelectionReference],System.Boolean,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.OnConfigureCompleted() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BaseConfigure() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2+<>c[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ConfigureDelayedBlueprints>b__12_0(BlueprintCore.Blueprints.CustomConfigurators.Configurator) (at :0)","System.Collections.Generic.List`1[[BlueprintCore.Blueprints.CustomConfigurators.Configurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1[BlueprintCore.Blueprints.CustomConfigurators.Configurator]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ConfigureDelayedBlueprints() (at :0)","TomeOfTheFirebird.BuildContent+BlueprintsCache_Init_Patch2.Postfix() (at :0)","Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Init_Patch194(Kingmaker.Blueprints.JsonSystem.BlueprintsCache) (at :0)","Kingmaker.Blueprints.JsonSystem.StartGameLoader.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch8(Kingmaker.Blueprints.JsonSystem.StartGameLoader) (at :0)","Kingmaker.GameStarter+<StartGameCoroutine>d__25.MoveNext() (at :0)","UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator,System.IntPtr) (at :0)"]}}
{"LogEvent":{"Severity":1,"Channel":"Mods","Message":"BlueprintCore.BlueprintConfigurator: CavalierTacticianAbilitySwift (BlueprintAbility) failed validation:\r\n  * Too many AbilityApplyEffect components. Only AbilityApplyFact applies..\r\n","StackTrace":["BlueprintCore.Utils.LogWrapper.Warn(System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.UnitLogic.Abilities.AbilityConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.AddBuffToAbilityApplyFact(Kingmaker.UnitLogic.Buffs.Blueprints.BlueprintBuff,BlueprintCore.Utils.Blueprint`1[Kingmaker.Blueprints.BlueprintReference`1[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility]]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.PopulateSelections(Kingmaker.Blueprints.Classes.BlueprintFeature,System.Collections.Generic.HashSet`1[Kingmaker.Blueprints.BlueprintFeatureSelectionReference],System.Boolean,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.OnConfigureCompleted() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BaseConfigure() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2+<>c[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ConfigureDelayedBlueprints>b__12_0(BlueprintCore.Blueprints.CustomConfigurators.Configurator) (at :0)","System.Collections.Generic.List`1[[BlueprintCore.Blueprints.CustomConfigurators.Configurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1[BlueprintCore.Blueprints.CustomConfigurators.Configurator]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ConfigureDelayedBlueprints() (at :0)","TomeOfTheFirebird.BuildContent+BlueprintsCache_Init_Patch2.Postfix() (at :0)","Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Init_Patch194(Kingmaker.Blueprints.JsonSystem.BlueprintsCache) (at :0)","Kingmaker.Blueprints.JsonSystem.StartGameLoader.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch8(Kingmaker.Blueprints.JsonSystem.StartGameLoader) (at :0)","Kingmaker.GameStarter+<StartGameCoroutine>d__25.MoveNext() (at :0)","UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator,System.IntPtr) (at :0)"]}}
{"LogEvent":{"Severity":0,"Channel":"[TomeOfTheFirebird] ","Message":"Patching Dispel IFF","StackTrace":[]}}
{"LogEvent":{"Severity":1,"Channel":"Mods","Message":"BlueprintCore.BlueprintConfigurator: DispelMagicGreaterArea (BlueprintAbility) failed validation:\r\n  * Too many AbilityApplyEffect components. Only AbilityEffectRunAction applies..\r\n","StackTrace":["BlueprintCore.Utils.LogWrapper.Warn(System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.UnitLogic.Abilities.AbilityConfigurator, TomeOfTheFirebird, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","TomeOfTheFirebird.Bugfixes.Abilities.AddIFFToDispels+BlueprintsCache_Init_Patch.Postfix() (at :0)","Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Init_Patch194(Kingmaker.Blueprints.JsonSystem.BlueprintsCache) (at :0)","Kingmaker.Blueprints.JsonSystem.StartGameLoader.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch8(Kingmaker.Blueprints.JsonSystem.StartGameLoader) (at :0)","Kingmaker.GameStarter+<StartGameCoroutine>d__25.MoveNext() (at :0)","UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator,System.IntPtr) (at :0)"]}}
{"LogEvent":{"Severity":0,"Channel":"[AF+Main] ","Message":"Configuring delayed.","StackTrace":[]}}
{"LogEvent":{"Severity":1,"Channel":"Mods","Message":"BlueprintCore.BlueprintConfigurator: CavalierTacticianAbility (BlueprintAbility) failed validation:\r\n  * Too many AbilityApplyEffect components. Only AbilityApplyFact applies..\r\n","StackTrace":["BlueprintCore.Utils.LogWrapper.Warn(System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.UnitLogic.Abilities.AbilityConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.AddBuffToAbilityApplyFact(Kingmaker.UnitLogic.Buffs.Blueprints.BlueprintBuff,BlueprintCore.Utils.Blueprint`1[Kingmaker.Blueprints.BlueprintReference`1[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility]]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.PopulateSelections(Kingmaker.Blueprints.Classes.BlueprintFeature,System.Collections.Generic.HashSet`1[Kingmaker.Blueprints.BlueprintFeatureSelectionReference],System.Boolean,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.OnConfigureCompleted() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BaseConfigure() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2+<>c[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ConfigureDelayedBlueprints>b__12_0(BlueprintCore.Blueprints.CustomConfigurators.Configurator) (at :0)","System.Collections.Generic.List`1[[BlueprintCore.Blueprints.CustomConfigurators.Configurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1[BlueprintCore.Blueprints.CustomConfigurators.Configurator]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ConfigureDelayedBlueprints() (at :0)","AddedFeats.Main+BlueprintCacheInitHandler.AfterBlueprintCachePatches() (at E:\\GitHub\\AddedFeats\\Main.cs:58)","AddedFeats.Utils.IBlueprintCacheInitHandler+StartGameLoader_LoadPackTOC_EventHandler+<>c.<Postfix>b__1_0(AddedFeats.Utils.IBlueprintCacheInitHandler) (at E:\\GitHub\\AddedFeats\\Utils\\IBlueprintCacheInitHandler.cs:40)","Kingmaker.PubSubSystem.SubscriptionManager`1[[Kingmaker.PubSubSystem.IGlobalSubscriber, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecuteActionInternal(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],AddedFeats.Utils.IBlueprintCacheInitHandler) (at :0)","Kingmaker.PubSubSystem.SubscriptionManager`1[[Kingmaker.PubSubSystem.IGlobalSubscriber, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecuteAction(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],System.Object) (at :0)","Kingmaker.PubSubSystem.SubscriptionManager`1[[Kingmaker.PubSubSystem.IGlobalSubscriber, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].RaiseEvent(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],System.Boolean) (at :0)","Kingmaker.PubSubSystem.EventBus.RaiseEvent(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],System.Boolean) (at :0)","AddedFeats.Utils.IBlueprintCacheInitHandler+StartGameLoader_LoadPackTOC_EventHandler.Postfix() (at E:\\GitHub\\AddedFeats\\Utils\\IBlueprintCacheInitHandler.cs:40)","Kingmaker.Blueprints.JsonSystem.StartGameLoader.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch8(Kingmaker.Blueprints.JsonSystem.StartGameLoader) (at :0)","Kingmaker.GameStarter+<StartGameCoroutine>d__25.MoveNext() (at :0)","UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator,System.IntPtr) (at :0)"]}}
{"LogEvent":{"Severity":1,"Channel":"Mods","Message":"BlueprintCore.BlueprintConfigurator: CavalierTacticianAbilitySwift (BlueprintAbility) failed validation:\r\n  * Too many AbilityApplyEffect components. Only AbilityApplyFact applies..\r\n","StackTrace":["BlueprintCore.Utils.LogWrapper.Warn(System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.UnitLogic.Abilities.AbilityConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.AddBuffToAbilityApplyFact(Kingmaker.UnitLogic.Buffs.Blueprints.BlueprintBuff,BlueprintCore.Utils.Blueprint`1[Kingmaker.Blueprints.BlueprintReference`1[Kingmaker.UnitLogic.Abilities.Blueprints.BlueprintAbility]]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.PopulateSelections(Kingmaker.Blueprints.Classes.BlueprintFeature,System.Collections.Generic.HashSet`1[Kingmaker.Blueprints.BlueprintFeatureSelectionReference],System.Boolean,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator.OnConfigureCompleted() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Configure(System.Boolean) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Classes.BlueprintFeature, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.CustomConfigurators.Classes.FeatureConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BaseConfigure() (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2+<>c[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ConfigureDelayedBlueprints>b__12_0(BlueprintCore.Blueprints.CustomConfigurators.Configurator) (at :0)","System.Collections.Generic.List`1[[BlueprintCore.Blueprints.CustomConfigurators.Configurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1[BlueprintCore.Blueprints.CustomConfigurators.Configurator]) (at :0)","BlueprintCore.Blueprints.CustomConfigurators.RootConfigurator`2[[Kingmaker.Blueprints.Root.BlueprintRoot, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[BlueprintCore.Blueprints.Configurators.Root.RootConfigurator, AddedFeats, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ConfigureDelayedBlueprints() (at :0)","AddedFeats.Main+BlueprintCacheInitHandler.AfterBlueprintCachePatches() (at E:\\GitHub\\AddedFeats\\Main.cs:58)","AddedFeats.Utils.IBlueprintCacheInitHandler+StartGameLoader_LoadPackTOC_EventHandler+<>c.<Postfix>b__1_0(AddedFeats.Utils.IBlueprintCacheInitHandler) (at E:\\GitHub\\AddedFeats\\Utils\\IBlueprintCacheInitHandler.cs:40)","Kingmaker.PubSubSystem.SubscriptionManager`1[[Kingmaker.PubSubSystem.IGlobalSubscriber, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecuteActionInternal(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],AddedFeats.Utils.IBlueprintCacheInitHandler) (at :0)","Kingmaker.PubSubSystem.SubscriptionManager`1[[Kingmaker.PubSubSystem.IGlobalSubscriber, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecuteAction(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],System.Object) (at :0)","Kingmaker.PubSubSystem.SubscriptionManager`1[[Kingmaker.PubSubSystem.IGlobalSubscriber, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].RaiseEvent(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],System.Boolean) (at :0)","Kingmaker.PubSubSystem.EventBus.RaiseEvent(System.Action`1[AddedFeats.Utils.IBlueprintCacheInitHandler],System.Boolean) (at :0)","AddedFeats.Utils.IBlueprintCacheInitHandler+StartGameLoader_LoadPackTOC_EventHandler.Postfix() (at E:\\GitHub\\AddedFeats\\Utils\\IBlueprintCacheInitHandler.cs:40)","Kingmaker.Blueprints.JsonSystem.StartGameLoader.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch8(Kingmaker.Blueprints.JsonSystem.StartGameLoader) (at :0)","Kingmaker.GameStarter+<StartGameCoroutine>d__25.MoveNext() (at :0)","UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator,System.IntPtr) (at :0)"]}}
{"LogEvent":{"Severity":0,"Channel":"[COP+Main] ","Message":"Configuring feats delayed.","StackTrace":[]}}
{"LogEvent":{"Severity":0,"Channel":"[COP+EldritchHeritage] ","Message":"Configuring EldritchHeritage for TTT bloodlines","StackTrace":[]}}

**Comment by WittleWolfie** [comment]
Yeah this is just a vanilla bug that BPCore detects. They have an invalid blueprint. IIRC there is supposed to be an FX triggered but it does not.
