### ISSUE TITLE
ActionsBuilder OnPets() will always apply to all pets no matter what the type is.

### ISSUE THREAD

**Issue by Balkoth-dev** [WittleWolfie/WW-Blueprint-Core#87]
Example
```
Kingmaker.ElementsSystem.ActionList applyLifeLink = ActionsBuilder.New().OnPets(ActionsBuilder.New()
.ApplyBuffPermanent(GetGUID.SummonerLifeLinkBuff, isNotDispelable: true)
.Build(),
PetTypeExtensions.Eidolon).Build();
```
Expected behavior is that it will only apply to pets of a certain type. This will affect all pets no matter the type because AllPets is defaulted to true.
Fix I had to do was just to set the AllPets to false afterwards and it worked.
```
((ContextActionsOnPet)applyLifeLink.Actions[0]).AllPets = false;
```

**Comment by WittleWolfie** [comment]
Yeah I fucked the logic on this, need to swap the setting for AllPets... right now it accidentally sets to true if you _do_ specify so it's broken both ways.

**Comment by WittleWolfie** [comment]
Fix in next release
